# Generated by Django 3.2.19 on 2023-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../capture_logo_nbnr9p', upload_to='images/'),
        ),
    ]
